server:
  port: 8081

spring:
  config:
    import:
      - classpath:application-oauth2.yml
  security:
    oauth2:
      client:
        registration:
          oidc-client:
            authorization-grant-type: authorization_code
            client-id: oidc-client
            client-secret: secret
            redirect-uri: http://localhost:8080/login/oauth2/code/oidc-client
            scope:
              - openid
              - profile
        provider:
          oidc-client:
            authorization-uri: http://localhost:8082/oauth2/authorize
            token-uri: http://localhost:8082/oauth2/token
            user-info-uri: http://localhost:8082/oauth2/userinfo
            user-name-attribute: sub
            jwk-set-uri: http://localhost:8082/oauth2/jwks
            user-info-authentication-method: header
  jpa:
    open-in-view: false

logging:
  level:
    org.springframework.security: trace
    org.springframework.web.client.RestTemplate: trace
